imports:
    - { resource: 'config.*.yml', type: glob, ignore_errors: true }
    - { resource: TYPO3, type: env }

# Reasonable error handling by default
SYS:
    errorHandler: Helhum\Typo3ConfigHandling\Error\ErrorHandler
    productionExceptionHandler: Helhum\Typo3ConfigHandling\Error\ProductionExceptionHandler
    debugExceptionHandler: Helhum\Typo3ConfigHandling\Error\DebugExceptionHandler
    errorHandlerErrors: 32514
    exceptionalErrors: 4352
    systemLogLevel: 2
    systemLog: error_log

LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                { logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log' }
