imports:
    - { resource: 'config.*.yml', type: glob }
    - { resource: '../packages/*/Configuration/Distribution/*.yml', type: glob, ignore_errors: true }
    - { resource: 'config-env.yml' }
    # Fetch environment configuration on deploy targets if it exists
    - { resource: '../../shared/Configuration/config-env.yml', ignore_errors: true }

# Reasonable error handling by default
BE:
    explicitADmode: explicitAllow
    loginSecurityLevel: rsa
DB:
    Connections:
        Default:
            charset: utf8
FE:
    loginSecurityLevel: rsa
GFX:
    jpg_quality: '80'
    processor: GraphicsMagick
    processor_effects: -1
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log'
SYS:
    debugExceptionHandler: Helhum\TYPO3\ErrorHandling\Error\DebugExceptionHandler
    errorHandler: Helhum\TYPO3\ErrorHandling\Error\ErrorHandler
    errorHandlerErrors: 32514
    exceptionalErrors: 4352
    productionExceptionHandler: Helhum\TYPO3\ErrorHandling\Error\ProductionExceptionHandler
    systemLog: error_log
    systemLogLevel: 2
