imports:
    - { resource: config.yml }
    - { resource: config.extension.yml }
    - { resource: 'dev.config.*.yml', type: glob, ignore_errors: true }
    - { resource: TYPO3, type: env, ignore_errors: true }

SYS:
    displayErrors: 1
    devIPmask: '*'
    sqlDebug: 1
    enableDeprecationLog: file
    exceptionalErrors: 28930
    systemLogLevel: 0
BE:
    debug: true
    sessionTimeout: 31536000
FE:
    debug: true
MAIL:
    transport: mbox
    transport_mbox_file: %env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/sent-mails.log
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::DEBUG)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                - %env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-default.log
